### PR TITLE
documentation(JS-64348): Comitted the broken link issue fix in charts.

### PR DESCRIPTION
**Pull request by Swetha-Babu**

### CODE REVIEW

**Review by Bhuvanesh-V — APPROVED** [review]
This is fine.

**Comment by Bhuvanesh-V** [comment]
rebuild

**Comment by Swetha-Babu** [comment]
rebuild

**Review by Gowrimathi — APPROVED** [review]
Fine

**Review by Gowrimathi — APPROVED** [review]
Fine

**Pull request merged**
